default_job = "check-all"

summary = true
wrap = false
reverse = false

export_locations = true

[keybindings]
q = "back"
ctrl-c = "quit"
ctrl-r = "rerun"
s = "toggle-summary"
w = "toggle-wrap"
t = "toggle-backtrace"
g = "scroll-to-top"
shift-g = "scroll-to-bottom"
k = "scroll-lines(-1)"
j = "scroll-lines(1)"
ctrl-d = "scroll-pages(-1)"
ctrl-u = "scroll-pages(1)"
