palette = "catppuccin_macchiato"

add_newline = false

format = "$directory$git_branch$package$nix_shell$rust$nodejs$golang$character"

[character]
success_symbol = "\n[](green)"
error_symbol = "\n[](red)"

[directory]
style = "bold directory"
truncation_length = 5

[git_branch]
symbol = ""
style = "bold branch"

[package]
symbol = ""
style = "bold package"

[nix_shell]
symbol = ""
style = "bold #5072BD"

[rust]
symbol = ""
style = "bold #F74B00"

[nodejs]
symbol = ""
style = "bold #82CD28"

[golang]
symbol = ""
style = "bold #68D1DE"

[palettes.onedark]
black = "#576270"
red = "#F16372"
green = "#8CC570"
orange = "#DB975C"
yellow = "#DAB067"
blue = "#40B0F5"
purple = "#E36FEA"
cyan = "#00AEBA"
white = "#A9B2C0"
directory = "#E36FEA"
branch = "#E36FEA"
package = "#DAB067"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
directory = "#b7bdf8"
branch = "#c6a0f6"
package = "#eed49f"
