gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6da95"
      - bold
    inactiveBorderColor:
      - "#cad3f5"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    selectedRangeBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#8bd5ca"
    cherryPickedCommitFgColor:
      - "#8aadf4"
    unstagedChangesColor:
      - red

  showFileTree: true
  showListFooter: false
  showRandomTip: false
  showBottomLine: false
  showCommandLog: true
  showIcons: true

disableStartupPopups: true

notARepository: "skip"

keybinding:
  universal:
    return: "q"

os:
  editCommand: "nvim"
